### ISSUE TITLE
Empty Repo

### ISSUE THREAD

**Issue by owos** [bltlab/africanlp2021-wikidata-names#1]
Hi @j0ma, I wanted to remind you that the repo  has been empty  for over 3 years and I would love if I can get the data on github or on huggingface

**Comment by ConstantineLignos** [comment]
Hi @owos,
Thanks for your interest in this work! As the README says, the data is available in the "Releases" on GitHub. Here's the latest data release:
https://github.com/bltlab/africanlp2021-wikidata-names/releases/download/2021.04.18.1/wikidata_african_lang_names.tar.gz

The AfricaNLP 2021 paper was work in progress. The more mature version is ParaNames, which we expect will have a new code and data release this spring (although you can already work with what's there): https://github.com/bltlab/paranames.
